In [ ]:
import torch

In [ ]:
x = torch.tensor([1, 2, 3])  # 1D 텐서 생성
y = torch.ones(2, 3)         # 모든 값이 1인 2x3 텐서 생성
z = torch.zeros(4, 5)        # 모든 값이 0인 4x5 텐서 생성

print("X: ", x)
print("Y: ", y)
print("Z: ", z)

X:  tensor([1, 2, 3])
Y:  tensor([[1., 1., 1.],
        [1., 1., 1.]])
Z:  tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
# 텐서의 속성
print(x.shape)  # 텐서의 형태
print(y.size()) # 텐서의 크기
print(z.dtype)  # 텐서의 데이터 타입

torch.Size([3])
torch.Size([2, 3])
torch.float32


In [ ]:
# 기본연산
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = a + b  # 텐서 덧셈
d = a * b  # 텐서 곱셈

print("덧셈 결과:", c)
print("곱셈 결과:", d)

덧셈 결과: tensor([5, 7, 9])
곱셈 결과: tensor([ 4, 10, 18])


In [ ]:
# 행렬연산
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
C = torch.matmul(A, B)  # 행렬 곱셈

print("행렬 곱셈 결과:\n", C)

행렬 곱셈 결과:
 tensor([[19, 22],
        [43, 50]])


In [ ]:
# 크기가 3x3인 랜덤 텐서 생성
x = torch.rand(3, 3)
y = torch.rand(3, 3)

# 텐서의 합계
z = torch.sum(x)
print("합계:\n", z)

# 텐서의 최대값과 인덱스
z, idx = torch.max(x, dim=0)
print("최대값:\n", z)
print("최대값 인덱스:\n", idx)

합계:
 tensor(5.9073)
최대값:
 tensor([0.7388, 0.7634, 0.9726])
최대값 인덱스:
 tensor([1, 1, 2])


In [ ]:
# 연산의 브로드캐스킹
x = torch.tensor([1, 2, 3])
y = torch.tensor([[1], [2], [3]])
z = x + y  # 브로드캐스팅을 통한 덧셈 연산

print("덧셈 결과:\n", z)
print("x의 형태:", x.shape)
print("y의 형태:", y.shape)
print("z의 형태:", z.shape)

덧셈 결과:
 tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])
x의 형태: torch.Size([3])
y의 형태: torch.Size([3, 1])
z의 형태: torch.Size([3, 3])


In [ ]:
# 자동 미분 (Autograd),  autograd 모듈은 역전파를 통해 자동으로 기울기를 계산

x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()

out.backward()  # 역전파 수행
print(x.grad)   # x에 대한 기울기 출력

tensor([ 6.,  8., 10.])


In [ ]:
# requires_grad=True를 설정하여 텐서의 기울기를 계산하도록 지정
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# 함수 정의
z = x * y + y**2

# 역전파 수행
z.backward()

# 기울기 출력
print("x에 대한 기울기:", x.grad)
print("y에 대한 기울기:", y.grad)

x에 대한 기울기: tensor(3.)
y에 대한 기울기: tensor(8.)


In [ ]:
# 신경망 모듈 (nn.Module),  nn.Module은 신경망의 기본 모듈
import torch.nn as nn
import torch.nn.functional as F

class SimpleNN(nn.Module):
    def __init__(self): # 신경망의 계층을 정의하는 부분
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(784, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x): # 순전파를 정의하는 부분으로, 입력 데이터가 신경망을 통과하는 방식을 지정
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = SimpleNN()
print(model)

SimpleNN(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)


In [ ]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        # 첫 번째 합성곱 층
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, stride=1, padding=1)
        self.bn1 = nn.BatchNorm2d(32)  # 배치 정규화
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2, padding=0)  # 최대 풀링
        self.dropout1 = nn.Dropout(p=0.25)  # 드롭아웃

        # 두 번째 합성곱 층
        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=1, padding=1)
        self.bn2 = nn.BatchNorm2d(64)  # 배치 정규화
        self.dropout2 = nn.Dropout(p=0.25)  # 드롭아웃

        # 완전 연결 층
        self.fc1 = nn.Linear(64 * 7 * 7, 128)
        self.bn3 = nn.BatchNorm1d(128)  # 배치 정규화
        self.dropout3 = nn.Dropout(p=0.5)  # 드롭아웃
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.bn1(self.conv1(x))))
        x = self.dropout1(x)
        x = self.pool(F.relu(self.bn2(self.conv2(x))))
        x = self.dropout2(x)
        x = x.view(-1, 64 * 7 * 7)  # 평탄화
        x = F.relu(self.bn3(self.fc1(x)))
        x = self.dropout3(x)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

# 모델 초기화
model_cnn = CNN()
print(model)

SimpleNN(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)


In [ ]:
# 데이터 로딩 (Data Loading),  torch.utils.data.Dataset을 상속받아 사용자 정의 데이터셋 클래스 생성
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

dataset = CustomDataset(data, labels)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

NameError: name 'data' is not defined

In [ ]:
# 손실 함수 및 옵티마이저 설정
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [ ]:
# 학습 루프
for epoch in range(num_epochs):
    for inputs, labels in dataloader:
        optimizer.zero_grad()        # 기울기 초기화
        outputs = model(inputs)      # 모델 예측
        loss = criterion(outputs, labels)  # 손실 계산
        loss.backward()              # 역전파 수행
        optimizer.step()             # 가중치 업데이트

In [ ]:
# 평가 모드 전환
model.eval()
with torch.no_grad():
    for inputs, labels in dataloader:
        outputs = model(inputs)
        # 평가 코드 작성

In [ ]:
# GPU 사용 (Using GPU), 객체를 GPU로 이동
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
inputs, labels = inputs.to(device), labels.to(device)